name: mesmo
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - attrs=21.4.0
  - blosc=1.21.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.15.0
  - cfitsio=4.0.0
  - charset-normalizer=2.0.12
  - click=8.0.4
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contextily=1.2.0
  - cryptography=36.0.1
  - curl=7.82.0
  - cvxpy=1.2.0
  - cvxpy-base=1.2.0
  - cycler=0.11.0
  - ecos=2.0.10
  - expat=2.4.7
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.96
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.29.1
  - freetype=2.10.4
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.10.2
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=69.1
  - idna=3.3
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9e
  - json-c=0.15
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libcxx=12.0.1
  - libdap4=3.20.6
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.4.1
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libpq=14.2
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - mercantile=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - nspr=4.32
  - nss=3.74
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.4.1
  - pcre=8.45
  - pillow=9.0.1
  - pip=22.0.4
  - pixman=0.40.0
  - poppler=22.01.0
  - poppler-data=0.4.11
  - postgresql=14.2
  - proj=8.2.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - qdldl-python=0.1.5
  - rasterio=1.2.10
  - readline=8.1
  - requests=2.27.1
  - scipy=1.8.0
  - scs=3.2.0
  - setuptools=60.9.3
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.37.0
  - tiledb=2.7.1
  - tk=8.6.12
  - tzcode=2021e
  - tzdata=2021e
  - unicodedata2=14.0.0
  - urllib3=1.26.8
  - wheel=0.37.1
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.3.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.1
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - bleach==4.1.0
    - blessed==1.19.1
    - bokeh==2.4.2
    - cachetools==5.0.0
    - colorcet==3.0.0
    - colorful==0.5.4
    - deprecated==1.2.13
    - dill==0.3.4
    - dss-python==0.10.7.post1
    - filelock==3.6.0
    - frozenlist==1.3.0
    - future==0.18.2
    - google-api-core==2.7.1
    - google-auth==2.6.0
    - googleapis-common-protos==1.55.0
    - gpustat==1.0.0b1
    - grpcio==1.43.0
    - gurobipy==9.5.1
    - h5py==3.6.0
    - hiredis==2.0.0
    - holoviews==1.14.8
    - hvplot==0.7.3
    - importlib-metadata==4.11.2
    - importlib-resources==5.4.0
    - jinja2==3.0.3
    - jsonschema==4.4.0
    - kaleido==0.2.1
    - markdown==3.3.6
    - markupsafe==2.1.0
    - msgpack==1.0.3
    - multidict==6.0.2
    - multimethod==1.7
    - natsort==8.1.0
    - networkx==2.7.1
    - nvidia-ml-py3==7.352.0
    - opencensus==0.8.0
    - opencensus-context==0.1.2
    - opencv-python==4.5.5.64
    - opendssdirect-py==0.6.1
    - panel==0.12.6
    - param==1.12.0
    - parameterized==0.8.1
    - plotly==5.6.0
    - prometheus-client==0.13.1
    - protobuf==3.19.4
    - psutil==5.9.0
    - psychrolib==2.5.0
    - pvlib==0.9.0
    - py-spy==0.3.11
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyct==0.4.8
    - pyrsistent==0.18.1
    - pyviz-comms==2.1.0
    - pyyaml==6.0
    - ray==1.11.0
    - redis==4.1.4
    - rsa==4.8
    - smart-open==5.2.1
    - tenacity==8.0.1
    - tornado==6.1
    - tqdm==4.63.0
    - typing-extensions==4.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - wrapt==1.14.0
    - yarl==1.7.2
    - zipp==3.7.0
