name: mesmo
channels:
  - conda-forge
dependencies:
  - affine=2.3.0
  - attrs=21.2.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - contextily=1.2.0
  - cryptography=35.0.0
  - curl=7.79.1
  - cvxpy=1.1.15
  - cvxpy-base=1.1.15
  - cycler=0.10.0
  - expat=2.4.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.9.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.1
  - intel-openmp=2021.4.0
  - jbig=2.1
  - joblib=1.1.0
  - jpeg=9d
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libdeflate=1.8
  - libffi=3.4.2
  - libgdal=3.3.2
  - libglib=2.70.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.4.3
  - mercantile=1.2.1
  - mkl=2021.4.0
  - msys2-conda-epoch=20160418
  - numpy=1.21.3
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - osqp=0.6.2
  - pandas=1.3.4
  - pcre=8.45
  - pillow=8.3.2
  - pip=21.3.1
  - pixman=0.40.0
  - poppler=21.09.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.1.1
  - pycparser=2.20
  - pyopenssl=21.0.0
  - pyparsing=3.0.1
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - qdldl-python=0.1.5
  - rasterio=1.2.10
  - requests=2.26.0
  - scipy=1.7.1
  - scs=2.1.4
  - setuptools=58.2.0
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.36.0
  - tbb=2021.4.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tornado=6.1
  - ucrt=10.0.20348.0
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wheel=0.37.0
  - win_inet_pton=1.1.0
  - xerces-c=3.2.3
  - xyzservices=2021.10.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - aiohttp==3.7.4.post0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - ansicon==1.89.0
    - async-timeout==3.0.1
    - bleach==4.1.0
    - blessed==1.19.0
    - bokeh==2.4.1
    - cachetools==4.2.4
    - colorcet==2.0.6
    - colorful==0.5.4
    - dill==0.3.4
    - dss-python==0.10.7.post1
    - ecos==2.0.7.post1
    - filelock==3.3.1
    - future==0.18.2
    - google-api-core==2.2.0
    - google-auth==2.3.2
    - googleapis-common-protos==1.53.0
    - gpustat==1.0.0b1
    - grpcio==1.41.1
    - gurobipy==9.1.2
    - h5py==3.5.0
    - hiredis==2.0.0
    - holoviews==1.14.6
    - hvplot==0.7.3
    - jinja2==3.0.2
    - jinxed==1.1.0
    - jsonschema==4.1.2
    - kaleido==0.2.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - msgpack==1.0.2
    - multidict==5.2.0
    - multimethod==1.6
    - natsort==7.1.1
    - networkx==2.6.3
    - nvidia-ml-py3==7.352.0
    - opencensus==0.8.0
    - opencensus-context==0.1.2
    - opencv-python==4.5.4.58
    - opendssdirect-py==0.6.1
    - packaging==21.0
    - panel==0.12.4
    - param==1.12.0
    - parameterized==0.8.1
    - plotly==5.3.1
    - prometheus-client==0.11.0
    - protobuf==3.19.0
    - psutil==5.8.0
    - psychrolib==2.5.0
    - pvlib==0.9.0
    - py-spy==0.3.10
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyct==0.4.8
    - pyrsistent==0.18.0
    - pyviz-comms==2.1.0
    - pyyaml==6.0
    - ray==1.7.1
    - redis==3.5.3
    - rsa==4.7.2
    - tenacity==8.0.1
    - tqdm==4.62.3
    - typing-extensions==3.10.0.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - yarl==1.7.0
