name: mesmo
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1
  - attrs=22.1.0
  - blosc=1.21.1
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.14
  - cairo=1.16.0
  - certifi=2022.9.14
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charset-normalizer=2.1.1
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.5
  - contextily=1.2.0
  - contourpy=1.0.5
  - cryptography=37.0.4
  - curl=7.83.1
  - cvxpy=1.2.1
  - cvxpy-base=1.2.1
  - cycler=0.11.0
  - ecos=2.0.10
  - expat=2.4.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.3
  - freetype=2.12.1
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.2.0
  - geos=3.11.0
  - geotiff=1.7.1
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - intel-openmp=2022.1.0
  - joblib=1.2.0
  - jpeg=9e
  - kealib=1.4.15
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.83.1
  - libdeflate=1.14
  - libffi=3.4.2
  - libgdal=3.5.2
  - libglib=2.72.1
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.38
  - libpq=14.5
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzip=1.9.2
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.6.0
  - mercantile=1.2.1
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - numpy=1.23.3
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - osqp=0.6.2.post0
  - packaging=21.3
  - pandas=1.5.0
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - poppler=22.04.0
  - poppler-data=0.4.11
  - postgresql=14.5
  - proj=9.0.1
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.2.1
  - qdldl-python=0.1.5
  - rasterio=1.3.2
  - requests=2.28.1
  - scipy=1.9.1
  - scs=3.2.0
  - setuptools=65.3.0
  - six=1.16.0
  - snappy=1.1.9
  - snuggs=1.4.7
  - sqlite=3.39.3
  - tbb=2021.5.0
  - tiledb=2.11.3
  - tk=8.6.12
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xerces-c=3.2.3
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - aiohttp==3.8.3
    - aiohttp-cors==0.7.0
    - aiosignal==1.2.0
    - ansicon==1.89.0
    - astroid==2.12.10
    - async-timeout==4.0.2
    - bleach==5.0.1
    - blessed==1.19.1
    - bokeh==2.4.3
    - cachetools==5.2.0
    - click==8.0.4
    - colorcet==3.0.0
    - colorful==0.5.4
    - coverage==6.4.4
    - dill==0.3.5.1
    - distlib==0.3.6
    - dss-python==0.12.1
    - dynaconf==3.1.11
    - filelock==3.8.0
    - frozenlist==1.3.1
    - google-api-core==2.10.1
    - google-auth==2.11.1
    - googleapis-common-protos==1.56.4
    - gpustat==1.0.0
    - grpcio==1.43.0
    - gurobipy==9.5.2
    - h5py==3.7.0
    - holoviews==1.15.0
    - hvplot==0.8.1
    - importlib-metadata==4.12.0
    - importlib-resources==5.9.0
    - isort==5.10.1
    - jinja2==3.1.2
    - jinxed==1.2.0
    - jsonschema==4.16.0
    - kaleido==0.2.1
    - lazy-object-proxy==1.7.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - mccabe==0.7.0
    - mesmo==0.5.0
    - msgpack==1.0.4
    - multidict==6.0.2
    - multimethod==1.9
    - natsort==8.2.0
    - networkx==2.8.6
    - nvidia-ml-py==11.495.46
    - opencensus==0.11.0
    - opencensus-context==0.1.3
    - opencv-python-headless==4.6.0.66
    - opendssdirect-py==0.7.0
    - panel==0.13.1
    - param==1.12.2
    - parameterized==0.8.1
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - plotly==5.10.0
    - prometheus-client==0.13.1
    - protobuf==3.20.2
    - psutil==5.9.2
    - psychrolib==2.5.0
    - pvlib==0.9.3
    - py-spy==0.3.14
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyct==0.4.8
    - pydantic==1.10.2
    - pylint==2.15.3
    - pyrsistent==0.18.1
    - pyviz-comms==2.2.1
    - pyyaml==6.0
    - ray==2.0.0
    - rsa==4.9
    - smart-open==6.2.0
    - tenacity==8.1.0
    - tomli==2.0.1
    - tomlkit==0.11.4
    - tornado==6.2
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - virtualenv==20.16.5
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - wrapt==1.14.1
    - yarl==1.8.1
    - zipp==3.8.1
