name: mesmo
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - attrs=23.1.0
  - blosc=1.21.4
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cfitsio=4.2.0
  - charset-normalizer=3.1.0
  - click=8.1.3
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - contextily=1.3.0
  - contourpy=1.1.0
  - curl=8.1.2
  - cvxpy=1.3.1
  - cvxpy-base=1.3.1
  - cycler=0.11.0
  - ecos=2.0.11
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freetype=2.12.1
  - freexl=1.0.6
  - geographiclib=1.52
  - geopy=2.3.0
  - geos=3.11.2
  - geotiff=1.7.1
  - gettext=0.21.1
  - hdf4=4.2.15
  - hdf5=1.14.0
  - icu=72.1
  - idna=3.4
  - intel-openmp=2023.1.0
  - joblib=1.2.0
  - kealib=1.5.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.2
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.7.0
  - libglib=2.76.3
  - libhwloc=2.9.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libosqp=0.6.3
  - libpng=1.6.39
  - libpq=15.3
  - libqdldl=0.1.5
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxml2=2.11.4
  - libzip=1.9.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.7.1
  - mercantile=1.2.1
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - numpy=1.25.0
  - openjpeg=2.5.0
  - openssl=3.1.1
  - osqp=0.6.3
  - packaging=23.1
  - pandas=2.0.2
  - pcre2=10.40
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - platformdirs=3.8.0
  - pooch=1.7.0
  - poppler=23.05.0
  - poppler-data=0.4.12
  - postgresql=15.3
  - proj=9.2.1
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pyparsing=3.1.0
  - pysocks=1.7.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3
  - qdldl-python=0.1.5.post2
  - rasterio=1.3.7
  - requests=2.31.0
  - scs=3.2.3
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.42.0
  - tbb=2021.9.0
  - tiledb=2.13.2
  - tk=8.6.12
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wheel=0.40.0
  - win_inet_pton=1.1.0
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.5.0
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - aiohttp==3.8.4
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - ansicon==1.89.0
      - astroid==2.15.5
      - async-timeout==4.0.2
      - bleach==6.0.0
      - blessed==1.20.0
      - bokeh==3.1.1
      - cachetools==5.3.1
      - cffi==1.15.1
      - colorcet==3.0.1
      - colorful==0.5.5
      - coverage==7.2.7
      - dill==0.3.6
      - distlib==0.3.6
      - dss-python==0.14.3
      - dss-python-backend==0.13.3
      - dynaconf==3.1.12
      - exceptiongroup==1.1.1
      - filelock==3.12.2
      - frozenlist==1.3.3
      - google-api-core==2.11.1
      - google-auth==2.21.0
      - googleapis-common-protos==1.59.1
      - gpustat==1.1
      - grpcio==1.51.3
      - gurobipy==10.0.2
      - h5py==3.9.0
      - holoviews==1.16.2
      - hvplot==0.8.4
      - iniconfig==2.0.0
      - isort==5.12.0
      - jinja2==3.1.2
      - jinxed==1.2.0
      - jsonschema==4.17.3
      - kaleido==0.2.1
      - lazy-object-proxy==1.9.0
      - linkify-it-py==2.0.2
      - markdown==3.4.3
      - markdown-it-py==2.2.0
      - markupsafe==2.1.3
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mesmo==0.5.0
      - msgpack==1.0.5
      - multidict==6.0.4
      - multimethod==1.9.1
      - natsort==8.4.0
      - networkx==3.1
      - nvidia-ml-py==11.525.112
      - opencensus==0.11.2
      - opencensus-context==0.1.3
      - opencv-python-headless==4.7.0.72
      - opendssdirect-py==0.8.3
      - panel==1.1.1
      - param==1.13.0
      - parameterized==0.9.0
      - plotly==5.15.0
      - pluggy==1.2.0
      - prometheus-client==0.17.0
      - protobuf==4.23.3
      - psutil==5.9.5
      - psychrolib==2.5.0
      - pvlib==0.9.5
      - py-spy==0.3.14
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pyct==0.5.0
      - pydantic==1.10.9
      - pylint==2.17.4
      - pyrsistent==0.19.3
      - pytest==7.4.0
      - pyviz-comms==2.3.2
      - pyyaml==6.0
      - ray==2.5.1
      - rsa==4.9
      - scipy==1.10.1
      - smart-open==6.3.0
      - tenacity==8.2.2
      - tomli==2.0.1
      - tomlkit==0.11.8
      - tornado==6.3.2
      - tqdm==4.65.0
      - uc-micro-py==1.0.2
      - urllib3==1.26.16
      - virtualenv==20.21.0
      - wcwidth==0.2.6
      - webencodings==0.5.1
      - wrapt==1.15.0
      - yarl==1.9.2
