name: Python tests
on: [push]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-latest,
          macos-latest,
          ubuntu-latest
        ]
        python-version: ["3.7", "3.8", "3.9"]
    defaults:
      run:
        shell: bash -l {0}  # Required for conda commands.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
    - name: Install dependencies
      run: |
        conda create -n mesmo -c conda-forge python=${{ matrix.python-version }} contextily cvxpy numpy pandas scipy
        conda activate mesmo
        python development_setup.py
    - name: Run tests with coverage report
      run: |
        conda activate mesmo
        coverage run -m unittest discover tests
        coverage xml
    - name: Report coverage to Codecov
      if: always()
      continue-on-error: true
      uses: codecov/codecov-action@v2
    - name: Report coverage to Codacy
      if: always()
      continue-on-error: true
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
