name: Python tests
on: [push]

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 8
      matrix:
        os: [
          windows-latest,
          macos-latest,
          ubuntu-latest
        ]
        python-version: [3.7, 3.8]
    defaults:
      run:
        shell: bash -l {0}  # Required for conda commands.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v2
    - name: Install dependencies
      run: |
        conda create -n mesmo -c conda-forge python=${{ matrix.python-version }} contextily cvxpy numpy pandas scipy
        conda activate mesmo
        pip install -v -e .
    - name: Lint with flake8
      run: |
        conda activate mesmo
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run tests
      run: |
        conda activate mesmo
        pip install pytest pytest-subtests
        pytest tests
